/*
 * Rename captured SVG icons from content hashes to their real identity.
 *
 * Two identity sources, both carried inside the captured markup:
 *   - `class="lucide lucide-wand-sparkles ..."`  -> a Lucide icon, name known
 *   - `class="CopyInviteLinkButton_icon__ab12"`  -> the owning component
 *
 * Emits web/src/assets/icons/index.ts mapping stable names -> imported URLs.
 */
import fs from 'node:fs'
import path from 'node:path'

const DIR = path.resolve('web/src/assets/icons')
const files = fs.readdirSync(DIR).filter((f) => f.endsWith('.svg'))

const kebab = (s) =>
  s
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^A-Za-z0-9]+/g, '-')
    .toLowerCase()
    .replace(/^-|-$/g, '')

const used = new Set()
function unique(name) {
  let n = name
  let i = 2
  while (used.has(n)) n = `${name}-${i++}`
  used.add(n)
  return n
}

const rows = []

for (const file of files.sort()) {
  const full = path.join(DIR, file)
  const svg = fs.readFileSync(full, 'utf8')
  const classAttr = (svg.match(/class="([^"]+)"/) || [])[1] ?? ''

  let base = null
  let kind = 'unknown'

  const lucide = classAttr.match(/lucide-([a-z0-9-]+)/)
  if (lucide && !['svg', 'icon'].includes(lucide[1])) {
    base = `lucide-${lucide[1].replace(/-icon$/, '')}`
    kind = 'lucide'
  } else {
    // first CamelCase token before the CSS-module underscore
    const comp = classAttr.match(/^([A-Za-z0-9]+)(?:-module)?_([A-Za-z0-9]+)/)
    if (comp) {
      base = `${kebab(comp[1])}--${kebab(comp[2])}`
      kind = 'component'
    } else if (/^[a-z][a-z0-9-]*\.svg$/.test(file) && !/^studio-|^prejoin-/.test(file)) {
      base = file.replace(/\.svg$/, '')
      kind = 'named'
    }
  }

  if (!base) {
    // keep the capture ordinal so it stays addressable
    const ord = file.match(/(\d{3})\.svg$/)
    base = ord ? `unnamed-${ord[1]}` : kebab(file.replace(/\.svg$/, ''))
    kind = 'unnamed'
  }

  const name = unique(base)
  const target = `${name}.svg`
  if (target !== file) {
    fs.renameSync(full, path.join(DIR, target))
  }
  rows.push({ name, file: target, kind, classAttr: classAttr.slice(0, 80) })
}

/* index.ts - Vite resolves these to hashed URLs at build time */
const lines = [
  '/*',
  ' * Captured Studio icons.',
  ' * Generated by scripts/name-icons.mjs - do not edit by hand.',
  ' *',
  ' * Names come from the markup itself: Lucide icons keep their Lucide name,',
  ' * the rest are named after the component that rendered them.',
  ' * Prefer lucide-react for anything in the `lucide-*` set; those files are kept',
  ' * only as a visual reference.',
  ' */',
  '',
]

const byKind = {}
for (const r of rows) (byKind[r.kind] ||= []).push(r)

for (const [kind, list] of Object.entries(byKind)) {
  lines.push(`/* ---- ${kind} (${list.length}) ---- */`)
  for (const r of list) {
    const ident = r.name.replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase()).replace(/^[0-9]/, '_$&')
    lines.push(`export { default as ${ident} } from './${r.file}?url'`)
  }
  lines.push('')
}

fs.writeFileSync(path.join(DIR, 'index.ts'), lines.join('\n'), 'utf8')

fs.writeFileSync(
  path.join(DIR, 'icons.json'),
  JSON.stringify(rows, null, 2),
  'utf8',
)

const counts = Object.fromEntries(Object.entries(byKind).map(([k, v]) => [k, v.length]))
console.log('renamed', rows.length, 'icons')
console.log(counts)
console.log('\nlucide set:')
console.log('  ' + rows.filter((r) => r.kind === 'lucide').map((r) => r.name.replace('lucide-', '')).join(', '))
console.log('\nsample component icons:')
rows.filter((r) => r.kind === 'component').slice(0, 25).forEach((r) => console.log('  ' + r.name))
